"03" = { chapter_name = "chapter 3: simple sentences", exercises = [
    { type = "vocab", tasks = [
        { l1 = "bird", l2 = "waso", junk = [
            "soweli",
            "pipi",
            "kasi",
        ] },
        { l1 = "land animal", l2 = "soweli", junk = [
            "waso",
            "pipi",
            "kasi",
        ] },
        { l1 = "bug", l2 = "pipi", junk = [
            "soweli",
            "waso",
            "kasi",
        ] },
        { l1 = "plant", l2 = "kasi", junk = [
            "soweli",
            "pipi",
            "waso",
        ] },
        { l1 = "to eat", l2 = "moku", junk = [
            "kasi",
            "lukin",
            "sona",
        ] },
        { l1 = "to see", l2 = "lukin", junk = [
            "waso",
            "moku",
            "sona",
        ] },
        { l1 = "to know", l2 = "sona", junk = [
            "pipi",
            "moku",
            "lukin",
        ] },
    ] },
] }

"04" = { chapter_name = "lesson 4: adjectives", exercises = [
    { type = "vocab", tasks = [
        { l1 = "large", l2 = "suli", junk = [
            "lili",
            "wawa",
            "sona",
        ] },
        { l1 = "small", l2 = "lili", junk = [
            "suli",
            "suwi",
            "pona",
        ] },
        { l1 = "good", l2 = "pona", junk = [
            "ike",
            "kasi",
            "suwi",
        ] },
        { l1 = "bad", l2 = "ike", junk = [
            "wawa",
            "pipi",
            "suli",
        ] },
        { l1 = "strong", l2 = "wawa", junk = [
            "suli",
            "soweli",
            "lili",
        ] },
        { l1 = "cute", l2 = "suwi", junk = [
            "pona",
            "waso",
            "lili",
        ] },
    ] },
] }
