name: Build Typst PDF

on:
  push:
    branches:
      - main
      - "**"
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Typst
        run: |
          curl -L https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz -o typst.tar.xz
          tar -xf typst.tar.xz
          sudo mv typst-*/typst /usr/local/bin/typst

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install fonts-texgyre

      - name: Compile Typst file
        run: |
          mkdir out
          typst compile osawi/osawi.typ out/osawi.pdf
          typst compile kemeka/main.typ out/kemeka.pdf
          typst compile wasona/wasona.typ out/wasona.pdf

      # - name: Upload artifact (always)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: typst-pdf
      #     path: osawi/osawi.pdf

      # release:
      #   needs: build
      #   runs-on: ubuntu-latest

      #   steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4

      # - name: Download built PDF
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: typst-pdf

      - name: Delete old releases
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          releases=$(gh release list --json tagName -q '.[].tagName')
          for tag in $releases; do
            gh release delete "$tag" --yes || true
          done

      # - name: Delete old artifacts
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     artifacts=$(gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[].id')
      #     for id in $artifacts; do
      #       gh api repos/${{ github.repository }}/actions/artifacts/$id -X DELETE || true
      #     done

      - name: Create new release
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "latest" osawi/* --title "Latest PDFs" --notes "PDFs built with Typst"
